### ISSUE TITLE
بعد از vendor  publish فایل کانفیگ اصلا بین گزینه ها نمیاد که داخل کانفیگ قرار بگیره

### ISSUE THREAD

**Issue by alihastam** [shetabit/captcha#2]
بعد از vendor  publish فایل کانفیگ اصلا بین گزینه ها نمیاد که داخل کانفیگ قرار بگیره

**Comment by khanzadimahdi** [comment]
این پکیج خیلی وقته توسعه داده نشده. بهتره ازش استفاده نکنید تا دوباره توسعه داده بشه و ورژن جدیدی براش منتشر بشه

**Comment by khanzadimahdi** [comment]
در هر صورت اگه میخواید ازش استفاده کنید سرویس پروایدرش رو توی اپلیکیشن کانفیگ لاراول معرفی کنید بعدش میتونید وندور رو پابلیش کنید
